import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "../features/navigation/navigation";
import "./globals.css";
//import backgroundImage from "../img/steve-a-johnson-jPT1hVOhqb0-unsplash.jpg";
//import backgroundImage from "@/public/guillaume-galtier-3YrppYQPoCI-unsplash.jpg";
//import backgroundImage from "@/public/kenrick-mills-ppY9ZjLjB0o-unsplash.jpg";
import backgroundImage from "@/public/pawel-czerwinski-95QNbCkVERM-unsplash.jpg";

import { Manrope } from "next/font/google";
import { PageNav } from "@/features/page-nav/page-nav";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${manrope.className}`}
    >
      <body className="min-h-full flex justify-center items-center">
        <div
          className="z-0 absolute inset-0 bg-cover bg-center bg-fixed opacity-100 blur-xs dark:opacity-30"
          style={{
            backgroundImage: `url(${backgroundImage.src})`,
          }}
        >
          <div className="z-5 absolute inset-0 bg-cover bg-center bg-fixed bg-black/0 "></div>
        </div>
        {/* <div className="absolute inset-0 bg-slate-100"> */}
        {/*   <div className="absolute inset-0 bg-[linear-gradient(to_right,#dfe3e8_1px,transparent_1px),linear-gradient(to_bottom,#dfe3e8_1px,transparent_1px)] bg-[size:48px_48px]" /> */}
        {/* </div> */}

        <div className="z-10 max-w-[1440px] md:h-[95vh] mx-auto flex  md:rounded-4xl overflow-hidden  shadow-[0_40px_120px_rgba(0,0,0,0.15)]">
          <Nav />
          <main className="mx-auto overflow-y-auto [scrollbar-width:none]  bg-[var(--background)]/92 py-3 ">
            <PageNav></PageNav>
            {children}
            {/* <div className="absolute -top-15 -right-15 bg-radial blur-2xl from-[#ecb7b7]/50 to-[#ecb7b7]/73 rounded-[50px] w-50 h-50 z-1000"></div> */}
          </main>

          <footer></footer>
        </div>
      </body>
    </html>
  );
}
