import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/navigation";
import "./globals.css";
import backgroundImage from "../img/steve-a-johnson-jPT1hVOhqb0-unsplash.jpg";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${manrope.className}`}
    >
      <body className="min-h-full flex justify-center items-center">
        <div
          className="z-0 absolute inset-0 bg-cover bg-center bg-fixed opacity-30"
          style={{
            backgroundImage: `url(${backgroundImage.src})`,
          }}
        />
        <div className="z-10 max-w-[1440px] h-[95vh] mx-auto flex bg-[var(--background)] rounded-2xl overflow-hidden">
          <Nav />
          <main className="mx-auto overflow-y-auto">{children}</main>

          <footer></footer>
        </div>
      </body>
    </html>
  );
}
